CREATE TABLE arduino.table1(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	temperature VARCHAR(10) NOT NULL,
	humidity VARCHAR(10) NOT NULL,
	soilMoisture VARCHAR(10) NOT NULL,
	lightPresence VARCHAR(10) NOT NULL) 